stories_it = [
	{"incipit": "Nella penombra serale", "finale": "qualcosa cambiò per sempre."},
	{"incipit": "Seguendo il suo istinto", "finale": "prese un'altra strada."},
	{"incipit": "Riflesso nell'acqua", "finale": "svelò antichi segreti."},
	{"incipit": "Finita l'estate", "finale": "nacque una tenera amicizia."},
	{"incipit": "Svoltato l'angolo", "finale": "riesumò ricordi sepolti."},
	{"incipit": "Il vento trasportava qualcosa", "finale": "eccheggiò un richiamo."},
	{"incipit": "Osservate le stelle", "finale": "si rimise in viaggio."},
	{"incipit": "Nascosta tra le pagine", "finale": "trovò una foglia."},
	{"incipit": "Sentì un brivido", "finale": "quando udì quel richiamo."},
	{"incipit": "Quando fece notte", "finale": "si unirono indissolubilmente."},
	{"incipit": "La luce riverberò", "finale": "lo chiuse."},
	{"incipit": "Aveva un obiettivo", "finale": "ma era troppo lontano."},
	{"incipit": "Con il passare delle stagioni", "finale": "cambiò ogni significato."},
	{"incipit": "L'oscurità penetrante", "finale": "coprì ogni cosa."},
	{"incipit": "Pensieri fugaci", "finale": "disegnò quella mappa."},
	{"incipit": "Perse la memoria", "finale": "la creatura si addormentò."},
	{"incipit": "La pioggia era leggera", "finale": "sollevò nuove domande."},
	{"incipit": "Fluttuando", "finale": "prese forma."},
	{"incipit": "Il tempo passò", "finale": "la storia cambiò."},
    {"incipit": "Quando si addormentò", "finale": "si risvegliò in un altro mondo."},
    {"incipit": "Quando si svegliò", "finale": "il dinosauro era ancora lì."},
    {"incipit": "Quella pianta era affascinante", "finale": "era buonissima."},
    {"incipit": "Quando sentì quel profumo", "finale": "ne colse un fiore."},
    {"incipit": "Consapevole di essere altro", "finale": "si trasformò in qualcos'altro."},
	{"incipit": "Alla deriva", "finale": "assunse forma"},
    {"incipit": "Nella conversazione", "finale": "perché no."},
    {"incipit": "Le stanze sono ampie", "finale": "e passano i decenni."},
    {"incipit": "Nelle sue foto", "finale": "a parte il silenzio."},
    {"incipit": "Senza che cambi niente", "finale": "è una bella domanda."},
    {"incipit": "Come previsto", "finale": "sono ancora ben visibili."},
    {"incipit": "Per farla breve", "finale": "non è andata benissimo."},
    {"incipit": "Un breve sguardo", "finale": "in un paese straniero."},
    {"incipit": "Da quel momento", "finale": "non esiste più."},
    {"incipit": "Con mia grande sorpresa", "finale": "di plastica bianchi o blu."},
    {"incipit": "Il mio ruolo", "finale": "sembrano piccole lentiggini."},
    {"incipit": "Il cancello d'ingresso", "finale": "dopo una separazione."},
    {"incipit": "La mia identità", "finale": "dai luoghi in cui si dorme."},
    {"incipit": "Molte delle piante", "finale": "nei sogni comprendiamo perfettamente."},
    {"incipit": "La risposta è complicata", "finale": "erano la stessa cosa."},
    {"incipit": "Insieme a quel ciliegio", "finale": "aspettare il 'secondo sonno'"},
    {"incipit": "Una piccola selva", "finale": "passano i decenni."},
    {"incipit": "L'importante è che", "finale": "sono esperienze collettive."}
]

stories_en = [
	{"incipit": "In the evening twilight", "finale": "something changed forever."},
	{"incipit": "Following his instincts", "finale": "he took another path."},
	{"incipit": "Reflected in the water", "finale": "revealed ancient secrets."},
	{"incipit": "Summer ended", "finale": "a tender friendship was born."},
	{"incipit": "Turned a corner", "finale": "dug up buried memories."},
	{"incipit": "The wind carried something", "finale": "echoed a call."},
	{"incipit": "Once looked at the stars", "finale": "set off again."},
	{"incipit": "Hidden between the pages", "finale": "found a leaf."},
	{"incipit": "They felt a chill", "finale": "when they heard that call."},
	{"incipit": "When night fell", "finale": "they became inseparably united."},
	{"incipit": "The light reverberated", "finale": "he closed it."},
	{"incipit": "They had a goal", "finale": "but they was too far away."},
    {"incipit": "With the passing of the seasons", "finale": "changed all meaning."},
	{"incipit": "Piercing darkness", "finale": "covered everything."},
	{"incipit": "Fleeting thoughts", "finale": "drew that map."},
	{"incipit": "They lost their memory", "finale": "the creature fell asleep."},
	{"incipit": "The rain was light", "finale": "raised new questions."},
	{"incipit": "Floating", "finale": "took shape."},
	{"incipit": "Time passed", "finale": "history changed."},
    {"incipit": "When they fell asleep", "finale": "he awoke in another world."},
    {"incipit": "When they woke up", "finale": "the dinosaur was still there."},
    {"incipit": "That plant was fascinating", "finale": "it was delicious."},
    {"incipit": "When they smelled that scent", "finale": "they picked a flower from it."},
    {"incipit": "Aware that they were something else", "finale": "they turned into something else."},
    {"incipit": "Drifting", "finale": "they assumed a shape."},
	{"incipit": "In conversation", "finale": "why not."},
    {"incipit": "The rooms are large", "finale": "and decades pass."},
    {"incipit": "In their pictures", "finale": "apart from the silence."},
    {"incipit": "Without anything changing", "finale": "it's a good question."},
    {"incipit": "As expected", "finale": "are still clearly visible."},
    {"incipit": "To make a long story short", "finale": "did not go well."},
    {"incipit": "A brief look", "finale": "in a foreign country."},
    {"incipit": "From that moment", "finale": "no longer exists."},
    {"incipit": "To my surprise", "finale": "of white or blue plastic."},
    {"incipit": "My role", "finale": "they look like little freckles."},
    {"incipit": "The entrance gate", "finale": "after a separation."},
    {"incipit": "My identity", "finale": "from sleeping places."},
    {"incipit": "Many of the plants", "finale": "in dreams we understand perfectly."},
    {"incipit": "The answer is complicated", "finale": "were the same thing."},
    {"incipit": "Together with that cherry tree", "finale": "waiting for the 'second sleep'"},
    {"incipit": "A little forest", "finale": "decades pass."},
    {"incipit": "The important thing is that", "finale": "they are collective experiences."}
]